name: Bump package version

on:
  workflow_call:  
  
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install bump2version
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Configure git
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Bump version
        shell: bash
        run: |
          bump2version patch --tag --verbose

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.INSPIRE_BOT_TOKEN }}
          repository: inspirehep/inpire-utils
          branch: ${{ github.ref }}
          tags: true
