name: Pull request master

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  python2_tests:
    uses: ./.github/workflows/test-python-2.yml

  python3_tests:
    uses: ./.github/workflows/test-python-3.yml

  bump_version:
    needs: [python2_tests, python3_tests]
    uses: ./.github/workflows/bump.yml
    secrets:
      PAT: ${{ secrets.INSPIRE_BOT_TOKEN }}
