name: Publish package

on:
  push:
    tags:
      - "*"
jobs:
  python2_tests:
    uses: ./.github/workflows/test-python-2.yml

  python3_tests:
    uses: ./.github/workflows/test-python-3.yml

  publish_package:
    needs: [python2_tests, python3_tests]
    uses: ./.github/workflows/publish.yml
